name: Tom Cotter
favicon: null
layout_spectrum: 0.43734
typography_spectrum: 0.38075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c161a'
    - '#a4cee0'
    - '#396174'
    - '#6694aa'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
